name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Ubuntu
      run: make setup-ubuntu
    - name: Run tests
      run: make ci

#  fuzz:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Setup fuzz
#      run: make -C fuzz setup-ubuntu
#    - name: Setup fuzz 2
#      run: make -C fuzz setup
#    - name: Run tests
#      run: make -C fuzz ci
